name: Windows Build

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib & hxcpp
        shell: cmd
        run: |
          mkdir %HOMEDRIVE%%HOMEPATH%\haxelib
          haxelib setup %HOMEDRIVE%%HOMEPATH%\haxelib
          haxelib install hxcpp > NUL
          .\setup\windows.bat

      - name: Skip SScript setup mode
        shell: cmd
        run: echo oy9:showMacroty8:loopCosti25y10:includeAllfg >> %USERPROFILE%\settings.cocoa

      - name: Create Version Tag
        shell: cmd
        run: echo %GITHUB_RUN_ID% > VERSION

      - name: Compile
        shell: cmd
        run: haxelib run lime build windows --app-version="4.0.0-%GITHUB_RUN_ID%" -D officialBuild

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
