name: Windows Build

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Haxe
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      # Setup haxelib
      - name: Setup Haxelib
        shell: cmd
        run: |
          if not exist "%HOMEDRIVE%%HOMEPATH%\haxelib" (
            mkdir "%HOMEDRIVE%%HOMEPATH%\haxelib"
          )

          haxelib setup "%HOMEDRIVE%%HOMEPATH%\haxelib"

      # Install required libraries
      - name: Install Dependencies
        shell: cmd
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hxcpp --quiet

      # Create version file
      - name: Create Version File
        shell: cmd
        run: |
          echo %GITHUB_RUN_ID% > VERSION

      # Build the game
      - name: Build Windows Release
        shell: cmd
        run: |
          call buildReleaseWindows.bat

      # Upload artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
          if-no-files-found: warn
