name: Build

on:
  workflow_call:
    inputs:
      buildFlags:
        required: false
        type: string
        default: ""

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib
        shell: cmd
        run: |
          if not exist "%HOMEDRIVE%%HOMEPATH%\haxelib" (
            mkdir "%HOMEDRIVE%%HOMEPATH%\haxelib"
          )

          haxelib setup "%HOMEDRIVE%%HOMEPATH%\haxelib"

      - name: Install Dependencies
        shell: cmd
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hxcpp --quiet

      - name: Build Windows
        shell: cmd
        run: |
          lime build windows -release -D %buildFlags%

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
          if-no-files-found: error
